'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión del motor en tiempo de ejecución:2.0.50727.8000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o vuelva a generar su proyecto de VS.
    '''<summary>
    '''  Clase de recurso con establecimiento inflexible de tipos, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class Idioma_pt
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PANTHER.Idioma_pt", GetType(Idioma_pt).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso con establecimiento inflexible de tipos.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ________________BOTONES_____________________.
        '''</summary>
        Public Shared ReadOnly Property ________________BOTONES_____________________() As String
            Get
                Return ResourceManager.GetString("________________BOTONES_____________________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _______________OPTIONS________________.
        '''</summary>
        Public Shared ReadOnly Property _______________OPTIONS________________() As String
            Get
                Return ResourceManager.GetString("_______________OPTIONS________________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _____________FORMAS_TITULOS________________.
        '''</summary>
        Public Shared ReadOnly Property _____________FORMAS_TITULOS________________() As String
            Get
                Return ResourceManager.GetString("_____________FORMAS_TITULOS________________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ____________FORMAS_SUB_TITULOS_____________.
        '''</summary>
        Public Shared ReadOnly Property ____________FORMAS_SUB_TITULOS_____________() As String
            Get
                Return ResourceManager.GetString("____________FORMAS_SUB_TITULOS_____________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ___________GRIDS_______________.
        '''</summary>
        Public Shared ReadOnly Property ___________GRIDS_______________() As String
            Get
                Return ResourceManager.GetString("___________GRIDS_______________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a _________LABELS_____________.
        '''</summary>
        Public Shared ReadOnly Property _________LABELS_____________() As String
            Get
                Return ResourceManager.GetString("_________LABELS_____________", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Agregar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Agregar() As String
            Get
                Return ResourceManager.GetString("Boton_Agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Borrar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Borrar() As String
            Get
                Return ResourceManager.GetString("Boton_Borrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Cerrar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Cerrar() As String
            Get
                Return ResourceManager.GetString("Boton_Cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Configurar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Configurar_Correo() As String
            Get
                Return ResourceManager.GetString("Boton_Configurar_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Consultar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Consultar() As String
            Get
                Return ResourceManager.GetString("Boton_Consultar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Envíar:.
        '''</summary>
        Public Shared ReadOnly Property Boton_Enviar_Correo() As String
            Get
                Return ResourceManager.GetString("Boton_Enviar_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Exportar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Exportar_Imagen() As String
            Get
                Return ResourceManager.GetString("Boton_Exportar_Imagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Guardar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Guardar() As String
            Get
                Return ResourceManager.GetString("Boton_Guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Imagen.
        '''</summary>
        Public Shared ReadOnly Property Boton_Imagen() As String
            Get
                Return ResourceManager.GetString("Boton_Imagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Aceptar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_Aceptar() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_Aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Cancelar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_Cancelar() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_Cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Eliminar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_Eliminar() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_Eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;No.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_No() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Salir.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_Salir() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_Salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Si.
        '''</summary>
        Public Shared ReadOnly Property Boton_Mensaje_Si() As String
            Get
                Return ResourceManager.GetString("Boton_Mensaje_Si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Modificar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Modificar() As String
            Get
                Return ResourceManager.GetString("Boton_Modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Nuevo.
        '''</summary>
        Public Shared ReadOnly Property Boton_Nuevo() As String
            Get
                Return ResourceManager.GetString("Boton_Nuevo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Programar.
        '''</summary>
        Public Shared ReadOnly Property Boton_Programar_Correo() As String
            Get
                Return ResourceManager.GetString("Boton_Programar_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Receta.
        '''</summary>
        Public Shared ReadOnly Property Boton_Receta() As String
            Get
                Return ResourceManager.GetString("Boton_Receta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Alimentos.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Alimentos() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Alimentos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Consultas.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Consultas() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Consultas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Desparasitación.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Desparasitacion() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Desparasitacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ec&amp;toparásitos.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Ectos() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Ectos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Estética.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Estetica() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Estetica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Otros.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Otros() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Otros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Vacunas.
        '''</summary>
        Public Shared ReadOnly Property Boton_Servicios_Vacunas() As String
            Get
                Return ResourceManager.GetString("Boton_Servicios_Vacunas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Ver.
        '''</summary>
        Public Shared ReadOnly Property Boton_Ver_Imagen() As String
            Get
                Return ResourceManager.GetString("Boton_Ver_Imagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Dueño con más mascotas:.
        '''</summary>
        Public Shared ReadOnly Property Etiqueta_Dueño_Mas_Mascotas() As String
            Get
                Return ResourceManager.GetString("Etiqueta_Dueño_Mas_Mascotas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Información.
        '''</summary>
        Public Shared ReadOnly Property Forma_Acerca_De() As String
            Get
                Return ResourceManager.GetString("Forma_Acerca_De", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agenda.
        '''</summary>
        Public Shared ReadOnly Property Forma_Agenda() As String
            Get
                Return ResourceManager.GetString("Forma_Agenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alta del médico.
        '''</summary>
        Public Shared ReadOnly Property Forma_Alta_Medico() As String
            Get
                Return ResourceManager.GetString("Forma_Alta_Medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alta del paciente.
        '''</summary>
        Public Shared ReadOnly Property Forma_Alta_Paciente() As String
            Get
                Return ResourceManager.GetString("Forma_Alta_Paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Colores.
        '''</summary>
        Public Shared ReadOnly Property Forma_Catalogos_Color() As String
            Get
                Return ResourceManager.GetString("Forma_Catalogos_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especies y razas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Catalogos_Especie() As String
            Get
                Return ResourceManager.GetString("Forma_Catalogos_Especie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Citas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Citas() As String
            Get
                Return ResourceManager.GetString("Forma_Citas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Envío de citas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Correos_Citas() As String
            Get
                Return ResourceManager.GetString("Forma_Correos_Citas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configuración.
        '''</summary>
        Public Shared ReadOnly Property Forma_Correos_Configuracion() As String
            Get
                Return ResourceManager.GetString("Forma_Correos_Configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ofertas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Correos_Ofertas() As String
            Get
                Return ResourceManager.GetString("Forma_Correos_Ofertas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desparasitación.
        '''</summary>
        Public Shared ReadOnly Property Forma_Desparasitacion() As String
            Get
                Return ResourceManager.GetString("Forma_Desparasitacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ectoparásitos.
        '''</summary>
        Public Shared ReadOnly Property Forma_Ectos() As String
            Get
                Return ResourceManager.GetString("Forma_Ectos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clínica.
        '''</summary>
        Public Shared ReadOnly Property Forma_Empresa() As String
            Get
                Return ResourceManager.GetString("Forma_Empresa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estéticas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Estetica_General() As String
            Get
                Return ResourceManager.GetString("Forma_Estetica_General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estilistas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Estilistas() As String
            Get
                Return ResourceManager.GetString("Forma_Estilistas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Perfil.
        '''</summary>
        Public Shared ReadOnly Property Forma_Inicio_Perfil() As String
            Get
                Return ResourceManager.GetString("Forma_Inicio_Perfil", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Forma_Nuevo_Correo() As String
            Get
                Return ResourceManager.GetString("Forma_Nuevo_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Forma_Nuevo_Medico() As String
            Get
                Return ResourceManager.GetString("Forma_Nuevo_Medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Forma_Tipo_Configuracion() As String
            Get
                Return ResourceManager.GetString("Forma_Tipo_Configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Forma_Tipo_Sistema() As String
            Get
                Return ResourceManager.GetString("Forma_Tipo_Sistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vacunas.
        '''</summary>
        Public Shared ReadOnly Property Forma_Vacunas() As String
            Get
                Return ResourceManager.GetString("Forma_Vacunas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Enviados.
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Enviado() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Enviado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Gmail() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Gmail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Otro() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Otro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Outlook() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Outlook", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Por envíar:.
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Por_Enviar() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Por_Enviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a .
        '''</summary>
        Public Shared ReadOnly Property Option_Correo_Yahoo() As String
            Get
                Return ResourceManager.GetString("Option_Correo_Yahoo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Día.
        '''</summary>
        Public Shared ReadOnly Property Option_Dia() As String
            Get
                Return ResourceManager.GetString("Option_Dia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Mascota.
        '''</summary>
        Public Shared ReadOnly Property Option_Mascota() As String
            Get
                Return ResourceManager.GetString("Option_Mascota", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Mes.
        '''</summary>
        Public Shared ReadOnly Property Option_Mes() As String
            Get
                Return ResourceManager.GetString("Option_Mes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Apellido.
        '''</summary>
        Public Shared ReadOnly Property Option_Propietario_Apellido() As String
            Get
                Return ResourceManager.GetString("Option_Propietario_Apellido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Nombre.
        '''</summary>
        Public Shared ReadOnly Property Option_Propietario_Nombre() As String
            Get
                Return ResourceManager.GetString("Option_Propietario_Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Teléfono.
        '''</summary>
        Public Shared ReadOnly Property Option_Propietario_Telefono() As String
            Get
                Return ResourceManager.GetString("Option_Propietario_Telefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Raza.
        '''</summary>
        Public Shared ReadOnly Property Option_Raza() As String
            Get
                Return ResourceManager.GetString("Option_Raza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Semana.
        '''</summary>
        Public Shared ReadOnly Property Option_Semana() As String
            Get
                Return ResourceManager.GetString("Option_Semana", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Color:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Color() As String
            Get
                Return ResourceManager.GetString("Paciente_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Especie:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Especie() As String
            Get
                Return ResourceManager.GetString("Paciente_Especie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Fecha nac.:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Fecha_Nac() As String
            Get
                Return ResourceManager.GetString("Paciente_Fecha_Nac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fo&amp;to:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Foto() As String
            Get
                Return ResourceManager.GetString("Paciente_Foto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Color.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Color() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Especie.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Especie() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Especie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Nac..
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Fecha_Nac() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Fecha_Nac", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Foto.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Foto() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Foto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Nombre() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Observacion.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Observacion() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Observacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Raza.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Raza() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Raza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sexo.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Grid_Sexo() As String
            Get
                Return ResourceManager.GetString("Paciente_Grid_Sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Nombre:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Nombre() As String
            Get
                Return ResourceManager.GetString("Paciente_Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Observación:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Observacion() As String
            Get
                Return ResourceManager.GetString("Paciente_Observacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Raza:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Raza() As String
            Get
                Return ResourceManager.GetString("Paciente_Raza", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Sexo:.
        '''</summary>
        Public Shared ReadOnly Property Paciente_Sexo() As String
            Get
                Return ResourceManager.GetString("Paciente_Sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Colonia:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Colonia() As String
            Get
                Return ResourceManager.GetString("Propietario_Colonia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Co&amp;rreo:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Correo() As String
            Get
                Return ResourceManager.GetString("Propietario_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;C.P.:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_CP() As String
            Get
                Return ResourceManager.GetString("Propietario_CP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Dirección:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Direccion() As String
            Get
                Return ResourceManager.GetString("Propietario_Direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Colonia.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Colonia() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Colonia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correo.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Correo() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a C.P..
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_CP() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_CP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dirección.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Direccion() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Materno.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Materno() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Materno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Nombre() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paterno.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Paterno() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Paterno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Teléfono.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Tel() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tel 2..
        '''</summary>
        Public Shared ReadOnly Property Propietario_Grid_Tel2() As String
            Get
                Return ResourceManager.GetString("Propietario_Grid_Tel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A. &amp;Materno:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Materno() As String
            Get
                Return ResourceManager.GetString("Propietario_Materno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No&amp;mbre:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Nombre() As String
            Get
                Return ResourceManager.GetString("Propietario_Nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a A. &amp;Paterno:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Paterno() As String
            Get
                Return ResourceManager.GetString("Propietario_Paterno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a &amp;Tel:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Tel() As String
            Get
                Return ResourceManager.GetString("Propietario_Tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a T&amp;el2:.
        '''</summary>
        Public Shared ReadOnly Property Propietario_Tel2() As String
            Get
                Return ResourceManager.GetString("Propietario_Tel2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Dueño.
        '''</summary>
        Public Shared ReadOnly Property Titulo_Dueño() As String
            Get
                Return ResourceManager.GetString("Titulo_Dueño", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mascota.
        '''</summary>
        Public Shared ReadOnly Property Titulo_Mascota() As String
            Get
                Return ResourceManager.GetString("Titulo_Mascota", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
